---
language: python
python: "2.7"

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
   # Install ansible
   - pip install ansible
   # install galaxy role
   - ansible-galaxy install ivanbojer.paloaltonetworks
   # instasll pep8
   - pip install pycodestyle

script:
   - cd library; find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
